package com.sgm.navi.service.define.route;

public enum RoutePreferenceID {
    PREFERENCE_RECOMMEND, //高德推荐
    PREFERENCE_AVOIDCONGESTION,//躲避拥堵
    PREFERENCE_LESSCHARGE,//少收费
    PREFERENCE_NOTHIGHWAY,//不走高速
    PREFERENCE_FIRSTHIGHWAY,//高速优先
    PREFERENCE_FIRSTMAINROAD,//大路优先
    PREFERENCE_FASTESTSPEED,//速度最快
    PREFERENCE_AVOIDCONGESTION_AND_LESSCHARGE,//躲避拥堵+少收费
    PREFERENCE_AVOIDCONGESTION_AND_NOTHIGHWAY,//躲避拥堵+不走高速
    PREFERENCE_AVOIDCONGESTION_AND_FIRSTHIGHWAY,//躲避拥堵+高速优先
    PREFERENCE_LESSCHARGE_AND_NOTHIGHWAY,//少收费+不走高速
    PREFERENCE_AVOIDCONGESTION_AND_LESSCHARGE_AND_NOTHIGHWAY,//躲避拥堵+少收费+不走高速
    PREFERENCE_AVOIDCONGESTION_AND_FIRSTMAINROAD,//躲避拥堵+大路优先
    PREFERENCE_AVOIDCONGESTION_AND_FASTESTSPEED//躲避拥堵+速度最快
}