package com.fy.navi.service.define.layer.refix;

public enum LayerItemSearchParentType {
    SEARCH_PARENT_GAS,
    SEARCH_PARENT_GAS_DISCOUNTS,
    SEARCH_PARENT_CAR_WASH,
    SEARCH_PARENT_DELICIOUS_FOOD,
    SEARCH_PARENT_NONE,
    SEARCH_PARENT_SCENIC_SPOT,
    SEARCH_PARENT_CHARGESTATION,
}
