package com.sgm.navi.service.define.signal;

public interface SignalConst {

    interface L2_NOP {
        int CLOSE_TO_NOA_AREA_TRUE = 1;
        int STATUS_ACTIVE_INDICATION_ON_TRUE = 2;
        int STATUS_NORMAL_TO_OVERRIDE_INDICATION_ON_TRUE = 3;
        int STATUS_OVERRIDE_TO_NORMAL_INDICATION_ON_TRUE = 4;
        int CLOSE_TO_TIGHT_CURVE_INDICATION_ON_TRUE = 5;
        int INTO_TIGHT_CURVE_INDICATION_ON_TRUE = 6;
        int TAKE_STEERING_INDICATION_ON_TRUE = 7;
        int MERGE_INTO_MAIN_ROAD_TRUE = 8;
        int LANE_CHANGING_TO_FOLLOW_ROUTE_LEFT = 9;
        int LANE_CHANGING_TO_FOLLOW_ROUTE_RIGHT = 10;
        int TEXT_TO_SPEECH_LANE_CHANGE_ABORT_TRUE = 11;
        int DISTANCE_TO_RAMP_2000M_INDICATION_ON_TRUE = 12;
        int DISTANCE_TO_RAMP_500M_INDICATION_ON_TRUE = 13;
        int COMPLICATED_ROAD_CONDITION_LANE_CHANGE_FAILED_TRUE = 14;
        int CHANGING_TO_FAST_LANE_LEFT = 15;
        int CONFIRM_CHANGE_TO_FAST_LANE_LEFT = 16;
        int CHANGING_TO_FAST_LANE_RIGHT = 17;
        int CONFIRM_CHANGE_TO_FAST_LANE_RIGHT = 18;
        int EXIT_RAMP_TO_NON_LIMITED_ACCESS_ROAD_TRUE = 19;
        int DISTANCE_TO_END_500M_INDICATION_ON_TRUE = 20;
        int FINISHED_INDICATION_ON_TRUE = 21;
        int TAKE_VEHICLE_CONTROL_INDICATION_ON_TRUE = 22;
        int DEACTIVATION_REASON_CONSTRUCTION = 23;
        int DEACTIVATION_REASON_MAP_UNAVAILABLE = 24;
        int DEACTIVATION_REASON_GPS_UNAVAILABLE = 25;
        int DEACTIVATION_REASON_TRAFFIC_JAM = 26;
        int DEACTIVATION_REASON_TIGHTCURVE = 27;
        int DEACTIVATION_REASON_SPEEDOUTLIMIT = 28;
        int DEACTIVATION_REASON_COMPLICATED_ROAD_CONDITION = 29;
        int DEACTIVATION_REASON_UNAVAILABLE = 30;
        int DEACTIVATION_REASON_TUNNEL = 31;
        int DEACTIVATION_REASON_SERVICE_NAVIGATION_ON_ADAS_SYSTEM = 32;
        int DEACTIVATION_REASON_DRIVER_ACTION = 33;
    }
}
